# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3148d2162ced12c86862b7f5c4f4d456cb719672a912b0ba73ce6f83ca3d95ac00e812da05e5046d8f9bbb23b87774a886eb2187b490f303657c851971c8dea0

test:
  secret_key_base: ad30a0451d0a2808b779ad5bd8c2754721e7c52628f4c059ac0e32e12645c5cc7b8c42a9063869d972109dfb09028b2759390fa1ae92ff60f550588fb54aa29d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
